### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by techsoldaten** [rhlowe/ember-text-placeholder#1]
This addon looks promising! Would love to see some documentation and would be happy to help write it. Noticed the following parameters. 
- size
- min
- varLength
- characters

**Comment by rhlowe** [comment]
Hi, yes, I actually have documentation, but its all in the wrong place, in the dummy app. I plan on moving it to the README soon!

**Comment by rhlowe** [comment]
I finally moved all the docs from the Dummy pages to the README!
